# Example workflow to use the reusable ci workflow
# This workflow is triggered by a pull request targeting
# the main or dev branch. It runs the CI tests
# for the specified Python versions
#
# * This workflow should be placed in `.github/workflows/ci.yml`
# of your repository.
name: CI

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test_and_lint:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    uses: AllenNeuralDynamics/aind-github-actions/.github/workflows/ci.yml@ci-32-trigger-conditions
    with:
      python-version: ${{ matrix.python-version }}